### ISSUE TITLE
Failing to build NPM package using ng-packagr

### ISSUE THREAD

**Issue by asarapas** [AckerApple/ack-angular-webcam#23]
Hi,
I'm struggling to get built NPM package using ng-packagr which has components with this ack-angular-webcam.

Here is build output:

`Building Angular library from [source_path]\ng-package.json
BUILD ERROR
'WebCamComponent' is not exported by node_modules\ack-angular-webcam\index.js
Error: 'WebCamComponent' is not exported by node_modules\ack-angular-webcam\index.js
    at error ([source_path]\node_modules\rollup\dist\rollup.js:185:14)
    at Module.error ([source_path]\node_modules\rollup\dist\rollup.js:8170:3)
    at Module.trace ([source_path]\node_modules\rollup\dist\rollup.js:8263:10)
    at ModuleScope.findDeclaration ([source_path]\node_modules\rollup\dist\rollup.js:7871:22)
    at Identifier.bind ([source_path]\node_modules\rollup\dist\rollup.js:6873:34)
    at eachChild.child ([source_path]\node_modules\rollup\dist\rollup.js:5674:34)
    at value.forEach.child ([source_path]\node_modules\rollup\dist\rollup.js:5683:38)
    at Array.forEach (native)
    at keys.forEach.key ([source_path]\node_modules\rollup\dist\rollup.js:5683:11)
    at Array.forEach (native)`

Would you have an idea what could be wrong and how could that be achieved?

**Comment by AckerApple** [comment]
My first guess is that your trying to import WebCamComponent from the index and that it is not exported from the index.

I can’t see your code so I’m just guessing. Are you importing the module from this package into your NgModule?

**Comment by AckerApple** [comment]
Also, I’m going to just ensure the component in the error is exported from the index as it should be

Hopefully today

**Comment by AckerApple** [comment]
Old issue. I did just check though and the component WebCamComponent is exported from the index. CLosing
